individual_household: C:\Users\User\Data_Mapping\X9400_no_attributes.csv
attributes: C:\Users\User\Data_Mapping\A2501E_ConnectionStepsAttributes.csv
giving: C:\Users\User\Data_Mapping\X1050_Giving.csv