individual_csv_headers = ('FamilyId',
                          'FamilyName',
                          'CreatedDate',
                          'PersonId',
                          'Prefix',
                          'FirstName',
                          'NickName',
                          'MiddleName',
                          'LastName',
                          'Suffix',
                          'FamilyRole',
                          'MaritalStatus',
                          'ConnectionStatus',
                          'RecordStatus',
                          'IsDeceased',
                          'HomePhone',
                          'MobilePhone',
                          'WorkPhone',
                          'SMS Allowed?',
                          'Email',
                          'IsEmailActive',
                          'Allow Bulk Email?',
                          'Gender',
                          'DateOfBirth',
                          'School',
                          'GraduationDate',
                          'AnniversaryDate',
                          'GeneralNote',
                          'MedicalNote',
                          'SecurityNote',
                          )

family_csv_headers = ('FormerName',
                      'SecondaryEmail',
                      'MembershipDate',
                      'SalvationDate',
                      'BaptismDate',
                      'FirstVisit',
                      'PreviousChurch',
                      'Occupation',
                      'Employer',
                      'Facebook',
                      'Instagram',
                      'Twitter',
                      )
