import unittest
from pandas import Series
import pandas as pd
import numpy.testing as npt

from F1toExcavatorMapper.Mapping.Family import FamilyBuilder


class MyTestCase(unittest.TestCase):
    states = ('tx',
              'LA',
              'Tn',
              'LA.',
              'AZ',
              'unknown',
              'OH',
              'IL',
              'AL',
              'CA',
              'MS',
              'VA',
              'MO',
              'OK',
              'GA',
              '71082',
              'Co',
              'NY',
              'FL',
              'AR.',
              '71110',
              'AE',
              'IA',
              'WY',
              'WA',
              'LALA',
              'SC',
              'MA',
              'AR',
              'Louisiana (LA)',
              'l',
              'WI',
              '77619',
              'KY',
              'OR',
              'MI',
              'AP',
              'Colorado',
              'Louisiana',
              'KS',
              'UT',
              'SD',
              ':A',
              'ls',
              'MD',
              'Tx.',
              'NM',
              '????',
              'LA`',
              '71129',
              'HI',
              '?????',
              'PA',
              '71107',
              'Illinois',
              '71111',
              'Missouri',
              'AK'
              )

    correct_states = pd.Series(('TX',
                                'LA',
                                'TN',
                                'LA',
                                'AZ',
                                '',
                                'OH',
                                'IL',
                                'AL',
                                'CA',
                                'MS',
                                'VA',
                                'MO',
                                'OK',
                                'GA',
                                '',
                                'CO',
                                'NY',
                                'FL',
                                'AR',
                                '',
                                'AE',
                                'IA',
                                'WY',
                                'WA',
                                '',
                                'SC',
                                'MA',
                                'AR',
                                '',
                                '',
                                'WI',
                                '',
                                'KY',
                                'OR',
                                'MI',
                                'AP',
                                '',
                                '',
                                'KS',
                                'UT',
                                'SD',
                                '',
                                'LS',
                                'MD',
                                'TX',
                                'NM',
                                '',
                                'LA',
                                '',
                                'HI',
                                '',
                                'PA',
                                '',
                                '',
                                '',
                                '',
                                'AK'
                                ))

    def test_clean_up_state(self):
        states = pd.Series(self.states).map(FamilyBuilder.clean_up_state)
        npt.assert_array_equal(self.correct_states, states)


if __name__ == '__main__':
    unittest.main()
