from enum import Enum

from F1toExcavatorMapper.Mapping.Mode import Mode
from F1toExcavatorMapper.Mapping.TargetCSVType import TargetCSVType


class SourceCSVType(Enum):
    INDIVIDUAL_HOUSEHOLD = (('Individual_ID',
                             'Member_Envelope',
                             'Barcode',
                             'Title',
                             'Prefix',
                             'First_Name',
                             'Goes_By',
                             'Middle_Name',
                             'Last_Name',
                             'Former_Name',
                             'Suffix',
                             'Household_Position',
                             'Gender',
                             'Marital_Status',
                             'Age',
                             'DOB',
                             'Status_Group',
                             'Status',
                             'Substatus',
                             'status_date',
                             'Status_Comment',
                             'Tag_Comment',
                             'Opt_In_Directory',
                             'Unsubscribed',
                             'Former_Denomination',
                             'School_Type',
                             'School',
                             'Employer',
                             'Occupation',
                             'Occupation_Desc',
                             'First_Record',
                             'Last_Updated',
                             'Last_Attended',
                             'Last_Activity_Attended',
                             'Last_Roster_Attended',
                             'last_contact_date',
                             'Last_Gave_On',
                             'Last_Gift',
                             'Preferred_Phone',
                             'Mobile_Phone',
                             'Work_Phone',
                             'Emergency_Phone',
                             'Preferred_Email',
                             'InFellowship_Email',
                             'Personal_Email',
                             'Facebook',
                             'Linkedin',
                             'Twitter',
                             'Household_Id',
                             'Household_Name',
                             'HH_First_Name',
                             'HH_Last_Name',
                             'HH_Preferred_Phone',
                             'HH_Preferred_Email',
                             'HH_Head_Name',
                             'HH_Head_DOB',
                             'HH_Head_Status',
                             'HH_Head_SubStatus',
                             'HH_Head_First_Record',
                             'HH_Head_Phone',
                             'HH_Head_Email',
                             'HH_Spouse_Name',
                             'HH_Spouse_DOB',
                             'HH_Spouse_Status',
                             'HH_Spouse_SubStatus',
                             'HH_Spouse_First_Record',
                             'HH_Spouse_Phone',
                             'HH_Spouse_Email',
                             'HH_Children',
                             'HH_Children_Ages',
                             'HH_Childs_Last_Attendance',
                             'AddressID',
                             'Street_Address',
                             'City',
                             'State_Province',
                             'Postal_Area',
                             'Postal_Code_5',
                             'Postal_Code',
                             'County',
                             'Country',
                             'Address_Comments',
                             'Verified',
                             'Attribute_Group',
                             'Attribute',
                             'Created_Date',
                             'Start_Date',
                             'End_Date',
                             'Pastor_Staff',
                             'Department',
                             'Comment'
                             ), (TargetCSVType.FAMILY, TargetCSVType.INDIVIDUAL), Mode.CREATE)

    ATTRIBUTES = (('individual_id_1,',
                   'attribute_group_name',
                   ',attribute_name	start_date,',
                   'end_date,comment'
                   ), [TargetCSVType.INDIVIDUAL], Mode.APPEND)

    def __init__(self, columns, target_types, mode):
        self.columns = columns
        self.target_types = target_types
        self.mode = mode
